spring:
  config:
    activate:
      on-profile: local, dev

# 프로퍼티 암호화 설정
jasypt:
  encryptor:
    bean: jasyptEncryptor
oauth2:
  kakao:
    client-id: ENC(LaIOX8XCg2xtcb5P6imVVAoKwuU39tOJpP+mpgVAWCRxzr0BsqbEvcx8h5geZXOI)
    client-secret: ENC(qmO5Z+MFfJ8FXkVxpLAiCczATIPz/r5nqLNfe9acuVfV9mU2/p4RVMth2F6soTDd)