spring:
  config:
    activate:
      on-profile: local, dev

# 프로퍼티 암호화 설정
jasypt:
  encryptor:
    bean: jasyptEncryptor
oauth2:
  kakao:
    client-id: ENC(GbZ2goEi4GCcFNdc8r/oVJdmTk1utaCwJr+sElrdPGulVdh7CyGCNGvmkqFSYXlb)
    client-secret: ENC(LIEhQuYvycnwyicmNo6digAyOKDqOYzyTsy6wwzC5IbFtIMEH9azHofes+cMvbzf)